name: streamlit
channels:
  - defaults
dependencies:
  - python=3.10.9
  - numpy=1.23.5
  - pandas=1.5.3
  - pip=23.0.1
  - pip:
      - matplotlib==3.7.1
      - plotly==5.13.1
      - simpy==4.0.1
      - streamlit==1.20.0
